export * from './lib/intercom-messenger.service'
export * from './lib/directives/hide.directive'
export * from './lib/intercom-messenger.module'
export * from './lib/directives/show.directive'
export * from './lib/directives/show-messages.directive'
export * from './lib/directives/show-new-message.directive'
export * from './lib/directives/shutdown.directive'
export * from './lib/directives/track-event.directive'
