name: Release

on:
  push:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'
      - run: npm ci
      - run: npm run lint:lib
      - run: npm run karma:lib
      - run: npm run build:lib
      - run: npm run cypress:lib:ct
      - run: npm run lint:demo
      - run: npm run karma:demo
      - run: npm run build:demo
      - run: npm run cypress:demo:ct
      - name: Run e2e
        run: |
          echo INTERCOM_APP_ID=${{ secrets.INTERCOM_APP_ID }} >> .env
          npm run cypress:demo:e2e
      - name: Publish
        working-directory: ./dist/ngx-intercom-messenger
        run: npm publish --access public --tag ${{github.ref_name == 'master' && 'latest' || 'next' }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
